### ISSUE TITLE
Need for polyfill on unsupported browsers?

### ISSUE THREAD

**Issue by hydrotik** [ldesplat/react-picture#1]
I'm on Mac 10.9.5 and not working in Safari 7.1.3 (showing the smallest image) and Chrome 44.0.2403.157 (if window is small it shows the smallest image, then responds as you scale the window up but then won't respond when making the window smaller again). Working on Firefox 33.1.1

``` javascript
render() {

    var imgs = [
      '//dummyimage.com/600x400/333/888.png&text=Full+Row 600w',
      '//dummyimage.com/900x600/777/fff.png&text=Full+Row 800w',
      '//dummyimage.com/1200x800/996666/333.png&text=Full+Row 1000w'
    ];

    return (
      <div className={styles.app}>
        <Header />
        <Carousel slides={this.state.slides} />
        <RowContainer>
            <ContentRow type='full'>
              <Img alt='Your picture description' srcSet={imgs.join(', ')} extra={{width:'100%'}} />
            </ContentRow>
        </RowContainer>
        <Body items={this.state.items} />
        <Footer />
      </div>
    );
  }
```

**Comment by ldesplat** [comment]
Thank you so much for opening the first issue :+1: 

Chrome 44, will use native support for srcset so none of the code will be executed. It just renders a normal `<img srcset='...'>` and the browser handles it. So you are at the whims of the browser for this.

Firefox 33 will use the implementation from this module.

Safari 7.1.3, now that's a bug. For the capability detection I just ensure that srcset is there but Microsoft Edge, Safari 7.1 and 8, iOS Safari 8 and 8.4 all have the srcset feature. The only problem with it is that they only implement using the `x` descriptor and not `w`.

Looks like we need to detect native support a bit more smartly and not just a boolean.

**Comment by ldesplat** [comment]
v0.0.4 has a strong chance of having fixed the issue with Safari.

Also now, if you use BaseImage instead of Image, you can pass `nativeSupport` property (by default `none`). Can be `none`, `partial`, `full`. Currently partial acts as none.

**Comment by hydrotik** [comment]
Thank you for getting back so quickly! I will take a look at this today and bring back my findings.

**Comment by hydrotik** [comment]
Yes, looking good in Safari. Still no luck on Chrome...

**Comment by ldesplat** [comment]
For Chrome, it will render it natively so will not have the same behavior. You are at the whim of the browser since Chrome supports srcset. So does your firefox version but they have different implementations.

If you really want to have the exact same behavior then you can do the following:
`var Img = require('react-picture').BaseImage`
This will by default disable nativeSupport and it will work the way you want it to in chrome.

Know, that it is much better to let the browser handle this stuff when they support it natively since they can do things I cannot. Like if you resize too fast, chrome will cancel requests for images that are in between. Things like that...

**Comment by hydrotik** [comment]
Good to know, I wonder if it's worth adding a condition for that. I'll do more tests on Windows as well, but thanks for your time on this!
